<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>
        <Version>18.0.1</Version>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <NoWarn>$(NoWarn);1591,1570,1572,1573</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
      <AssemblyTitle>Firebend Auto Crud IO</AssemblyTitle>
      <Description>Firebend Auto Crud extension pack for exporting entities to csvs or spreadsheets using ClosedXML and CsvHelper</Description>
      <PackageTags>firebend;autocrud;crud;io;csv;spreadsheet;excel</PackageTags>
      <Authors>Firebend</Authors>
      <RepositoryUrl>https://github.com/firebend/auto-crud</RepositoryUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageProjectUrl>https://github.com/firebend/auto-crud</PackageProjectUrl>
      <PackageIcon>nuget-image.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" />
      <PackageReference Include="CsvHelper" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Firebend.AutoCrud.Core\Firebend.AutoCrud.Core.csproj" />
    </ItemGroup>

</Project>
