<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>

        <IsPackable>false</IsPackable>

        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="AutoFixture.AutoMoq" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="GitHubActionsTestLogger">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Firebend.AutoCrud.ChangeTracking.EntityFramework\Firebend.AutoCrud.ChangeTracking.EntityFramework.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.ChangeTracking.Mongo\Firebend.AutoCrud.ChangeTracking.Mongo.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.ChangeTracking.Web\Firebend.AutoCrud.ChangeTracking.Web.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.CustomFields.Web\Firebend.AutoCrud.CustomFields.Web.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.EntityFramework\Firebend.AutoCrud.EntityFramework.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.Io\Firebend.AutoCrud.Io.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.Mongo\Firebend.AutoCrud.Mongo.csproj" />
      <ProjectReference Include="..\Firebend.AutoCrud.Web\Firebend.AutoCrud.Web.csproj" />
    </ItemGroup>


</Project>
