POST https://localhost:5001/api/v1/ef-person
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample"
}
###
PUT https://localhost:5001/api/v1/ef-person/f3d53eb0-9c2c-46ae-3f7d-08d8707b4bcc
Content-Type: application/json

{
    "id": "f3d53eb0-9c2c-46ae-3f7d-08d8707b4bcc",
    "firstName": "Simon",
    "lastName": "Sample"
}
###
PATCH https://localhost:5001/api/v1/ef-person/b12f7ead-9e94-4bb9-415f-08d870cf85d2
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Sample Patched"
    }
]
###
DELETE https://localhost:5001/api/v1/ef-person/f3d53eb0-9c2c-46ae-3f7d-08d8707b4bcc

###
https://localhost:5001/api/v1/ef-person/f3d53eb0-9c2c-46ae-3f7d-08d8707b4bcc

###
https://localhost:5001/api/v1/ef-person/all

###
https://localhost:5001/api/v1/ef-person?search=Simon&pageSize=10&pageNumber=1