POST https://localhost:5001/api/v1/ef-person
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "z"
}
###
PUT https://localhost:5001/api/v1/ef-person/b60b0fcd-fd29-4e05-8a29-08d87ac43f8e
Content-Type: application/json

{
    "id": "b60b0fcd-fd29-4e05-8a29-08d87ac43f8e",
    "firstName": "Simon",
    "lastName": "Sample Updated"
}
###
PATCH https://localhost:5001/api/v1/ef-person/e9c6a857-97e1-4e75-26ab-08d87772274c
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Sample Patch"
    }
]
###
DELETE https://localhost:5001/api/v1/ef-person/b60b0fcd-fd29-4e05-8a29-08d87ac43f8e

###
https://localhost:5001/api/v1/ef-person/9a627f6c-3fe2-4c18-bec9-08d87431b19f

###
https://localhost:5001/api/v1/ef-person/all

###
https://localhost:5001/api/v1/ef-person?search=Simon&pageSize=10&pageNumber=1

###
http://localhost:5000/api/v1/ef-person/e9c6a857-97e1-4e75-26ab-08d87772274c/changes

###
http://localhost:5000/api/v1/ef-person/export/csv?filename=export

###
http://localhost:5000/api/v1/ef-person/export/spreadsheet?filename=export