POST https://localhost:5001/api/v1/ef-person
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "z"
}
###
PUT https://localhost:5001/api/v1/ef-person/7d963ef7-a42d-40c8-449d-08d87a83025c
Content-Type: application/json

{
    "id": "7d963ef7-a42d-40c8-449d-08d87a83025c",
    "firstName": "Jacob",
    "lastName": "Atchley",
    "nickName": "Jake"
}
###
PATCH https://localhost:5001/api/v1/ef-person/7d963ef7-a42d-40c8-449d-08d87a83025c
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Henry4"
    }
]
###
DELETE https://localhost:5001/api/v1/ef-person/b60b0fcd-fd29-4e05-8a29-08d87ac43f8e

###
https://localhost:5001/api/v1/ef-person/9a627f6c-3fe2-4c18-bec9-08d87431b19f

###
https://localhost:5001/api/v1/ef-person/all

###
https://localhost:5001/api/v1/ef-person?search=Simon&pageSize=10&pageNumber=1

###
http://localhost:5000/api/v1/ef-person/7d963ef7-a42d-40c8-449d-08d87a83025c/changes?pageNumber=1&pageSize=5

###
http://localhost:5000/api/v1/ef-person/export/csv?filename=export

###
http://localhost:5000/api/v1/ef-person/export/spreadsheet?filename=export