<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>
        <Version>17.0.1</Version>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <NoWarn>$(NoWarn);1591,1570,1572,1573</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
      <AssemblyTitle>Firebend Auto Crud Core</AssemblyTitle>
      <Description>Firebend Auto Crud</Description>
      <PackageTags>firebend;autocrud;crud;</PackageTags>
      <Authors>Firebend</Authors>
      <RepositoryUrl>https://github.com/firebend/auto-crud</RepositoryUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageProjectUrl>https://github.com/firebend/auto-crud</PackageProjectUrl>
      <PackageIcon>nuget-image.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AsyncKeyedLock" />
      <PackageReference Include="Firebend.JsonPatchGenerator" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Implementations\Logging" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Interfaces\Services\Logging\ILoggerAdaptor.cs" />
    </ItemGroup>

</Project>
