POST https://localhost:5001/api/v1/mongo-person
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample",
    "ignoreMe": "Todd"
}
###
PUT https://localhost:5001/api/v1/mongo-person/ff09e683-7aa9-4ae8-a4e3-1fa408b9ddd4
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample Updated"
}
###
PATCH https://localhost:5001/api/v1/mongo-person/443adfbc-71c4-4bef-b7d7-e7425dd27eed
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Sample Patch"
    }
]
###
DELETE https://localhost:5001/api/v1/mongo-person/f8ed4843-dcd9-42df-8028-3a4e4af66416

###
https://localhost:5001/api/v1/mongo-person/f8ed4843-dcd9-42df-8028-3a4e4af66416

###
https://localhost:5001/api/v1/mongo-person/all

###
https://localhost:5001/api/v1/mongo-person?search=todd&pageSize=10&pageNumber=1

###
http://localhost:5000/api/v1/mongo-person/443adfbc-71c4-4bef-b7d7-e7425dd27eed/changes?PageNumber=1&pageSize=20

###
https://localhost:5001/api/v1/mongo-person/export/csv/?fileName=test&search=Simon&pageSize=10&pageNumber=1

###

POST https://localhost:5001/api/v1/mongo-person/multiple
Content-Type: application/json

[
    {
        "firstName": "Fox",
        "lastName": "Mulder",
    },
    {
        "firstName": "Dana",
        "lastName": "Scully"
    }
]
###
POST http://localhost:5000/api/v1/mongo-person/38d3301a-ce8c-4dc3-8efd-a6f29e5bca31/custom-fields/
Content-Type: application/json

{
    "key" : "shirt size",
    "value": "xlarge"
}

###
PUT http://localhost:5000/api/v1/mongo-person/38d3301a-ce8c-4dc3-8efd-a6f29e5bca31/custom-fields/91df5294-696f-4f2f-a3cf-eb9f0c7f1fc3
Content-Type: application/json

{
    "key" : "shirt size",
    "value": "xx large"
}
