GET https://localhost:5001/api/v1/gc-collect
###
POST https://localhost:5001/api/v1/ef-person
Content-Type: application/json

{
    "firstName": "Peggy",
    "lastName": "Sue",
    "createdDate": "2020-01-01"
}
###
POST https://localhost:5001/api/v1/ef-person/multiple
Content-Type: application/json

[
    {
        "firstName": "Fox",
        "lastName": "Mulder",
        "nickName": "Spooky"
    },
    {
        "firstName": "Dana",
        "lastName": "Scully"
    }
]
###
PUT https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc
Content-Type: application/json

{
    "firstName": "Hank",
    "lastName": "Hill",
    "nickName": "Hanky Panky"
}
###
PATCH https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "replaced"
    }
]
###
DELETE https://localhost:5001/api/v1/ef-person/7ee52d91-16d3-474f-8d50-08d8be84119e

###
https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc

###
https://localhost:5001/api/v1/ef-person/all

###
https://localhost:5001/api/v1/ef-person?search=Fox&pageSize=10&pageNumber=1&modifiedStartDate=2021-01-12T15:24:22.285552-06:00

###
https://localhost:5001/api/v1/ef-person?nickName=Spooky&pageSize=10&pageNumber=1&modifiedStartDate=2021-01-12T15:24:22.285552-06:00

###
http://localhost:5000/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/changes?pageNumber=1&pageSize=20&modifiedStartDate=2021-01-12T15:24:22.285552-06:00

###
http://localhost:5000/api/v1/ef-person/export/spreadSheet?filename=export&pageSize=50&pageNumber=1

###
http://localhost:5000/api/v1/ef-person/export/csv?filename=export&pageNumber=1&pageSize=10

###
POST http://localhost:5000/api/v1/ef-person/1a9126c0-5d14-4804-6067-08d9af8c4fd0/custom-fields
Content-Type: application/json

{
    "key" : "shirt size",
    "value": "large"
}

###
PUT http://localhost:5000/api/v1/ef-person/dcfd240b-8a6c-4278-f821-08d8bf1a31b6/custom-fields/9a25b036-9b18-4c40-7a8f-08d904f665aa
Content-Type: application/json

{
    "key" : "shirt size",
    "value": "medium"
}

###
PATCH http://localhost:5000/api/v1/ef-person/dcfd240b-8a6c-4278-f821-08d8bf1a31b6/custom-fields/9a25b036-9b18-4c40-7a8f-08d904f665aa
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/value",
        "value": "xxl patch"
    }
]

###
DELETE http://localhost:5000/api/v1/ef-person/dcfd240b-8a6c-4278-f821-08d8bf1a31b6/custom-fields/9a25b036-9b18-4c40-7a8f-08d904f665aa
Content-Type: application/json

###
http://localhost:5000/api/v1/ef/domain-event-custom-context
