POST https://localhost:5001/api/v1/ef-person
Content-Type: application/json

{
    "firstName": "Peggy",
    "lastName": "Sue",
    "createdDate": "2020-01-01"
}
###
POST https://localhost:5001/api/v1/ef-person/multiple
Content-Type: application/json

[
    {
        "firstName": "Fox",
        "lastName": "Mulder",
        "nickName": "Spooky"
    },
    {
        "firstName": "Dana",
        "lastName": "Scully"
    }
]
###
PUT https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc
Content-Type: application/json

{
    "firstName": "Hank",
    "lastName": "Hill",
    "nickName": "Hanky Panky"
}
###
PATCH https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "replaced"
    }
]
###
DELETE https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc

###
https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc

###
https://localhost:5001/api/v1/ef-person/all

###
https://localhost:5001/api/v1/ef-person?search=Peggy&pageSize=20&pageNumber=1&modifiedStartDate=2020-11-05T15:24:22.285552-06:00

###
http://localhost:5000/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/changes?pageNumber=1&pageSize=20

###
http://localhost:5000/api/v1/ef-person/export/csv?filename=export&pageSize=50&pageNumber=1

###
http://localhost:5000/api/v1/ef-person/export/csv?filename=export
