POST https://localhost:5001/api/v1/ef-person/a2f9d44a-613c-42d2-41d3-08d884ca630d/pets
Content-Type: application/json

{
    "petName": "Frodo",
    "petType": "Dog"
}
###
GET https://localhost:5001/api/v1/ef-person/5eaa2c79-5709-43bb-9768-08d88bd03ee0/pets?pageNumber=1&pageSize=10
