POST https://localhost:5001/api/v1/ef-person//pets
Content-Type: application/json

{
    "petName": "Frodo",
    "petType": "Dog"
}
###
GET https://localhost:5001/api/v1/ef-person/dcfd240b-8a6c-4278-f821-08d8bf1a31b6/pets?pageNumber=1&pageSize=10

###
GET https://localhost:5001/api/v1/ef-person/dcfd240b-8a6c-4278-f821-08d8bf1a31b6/pets/1b3e5104-3e6c-4707-2fe0-08d8b6558ebc/changes?pageNumber=1&pageSize=10

###
GET https://localhost:5001/api/v1/ef-person/dcfd240b-8a6c-4278-f821-08d8bf1a31b6/pets/export/csv?pageNumber=1&pageSize=10&fileName=test
