POST https://localhost:5001/api/v1/mongo-person
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample"
}
###
PUT https://localhost:5001/api/v1/mongo-person/67739754-4145-4514-a509-15a36bc856ef
Content-Type: application/json

{
    "id": "60fcc388-0829-42a8-a49b-9006ea3d3080",
    "firstName": "Simon",
    "lastName": "Sample Updated"
}
###
PATCH https://localhost:5001/api/v1/mongo-person/60fcc388-0829-42a8-a49b-9006ea3d3080
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Sample Patch"
    }
]
###
DELETE https://localhost:5001/api/v1/mongo-person/60fcc388-0829-42a8-a49b-9006ea3d3080

###
https://localhost:5001/api/v1/mongo-person/60fcc388-0829-42a8-a49b-9006ea3d3080

###
https://localhost:5001/api/v1/mongo-person/all

###
https://localhost:5001/api/v1/mongo-person?search=Simon&pageSize=10&pageNumber=1

###
http://localhost:5000/api/v1/mongo-person/60fcc388-0829-42a8-a49b-9006ea3d3080/changes?PageSize=100&PageNumber=1
