POST https://localhost:5001/api/v1/mongo-person
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample",
    "ignoreMe": "Todd"
}
###
PUT https://localhost:5001/api/v1/mongo-person/ff09e683-7aa9-4ae8-a4e3-1fa408b9ddd4
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample Updated"
}

### should fail, you aren't allowed to put a custom field
###
PUT https://localhost:5001/api/v1/mongo-person/ff09e683-7aa9-4ae8-a4e3-1fa408b9ddd4
Content-Type: application/json

{
    "firstName": "Simon",
    "lastName": "Sample Updated",
    "customFields": [
        {
            "key": "fake",
            "value": "faker"
        }
    ]
}
###
PATCH https://localhost:5001/api/v1/mongo-person/3f3378a2-5956-4388-9e7a-8909f4f70a4f
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Sample Patch"
    }
]

### should fail, not allowed to patch custom fields
###
PATCH https://localhost:5001/api/v1/mongo-person/443adfbc-71c4-4bef-b7d7-e7425dd27eed
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/lastName",
        "value": "Sample Patch"
    },
    {
        "op": "add",
        "path": "/customFields/0",
        "value": { "key": "patch key", "value": "patchValue"  }
    }
]
###
DELETE https://localhost:5001/api/v1/mongo-person/f8ed4843-dcd9-42df-8028-3a4e4af66416

###
https://localhost:5001/api/v1/mongo-person/f8ed4843-dcd9-42df-8028-3a4e4af66416

###
https://localhost:5001/api/v1/mongo-person/all

###
https://localhost:5001/api/v1/mongo-person?search=todd&pageSize=10&pageNumber=1

###
https://localhost:5001/api/v1/mongo-person?nickName=todd&pageSize=10&pageNumber=1

###
https://localhost:5001/api/v1/mongo-person?pageSize=10&pageNumber=1
###
http://localhost:5000/api/v1/mongo-person/443adfbc-71c4-4bef-b7d7-e7425dd27eed/changes?PageNumber=1&pageSize=20

###
https://localhost:5001/api/v1/mongo-person/export/csv/?fileName=test&search=Simon&pageSize=10&pageNumber=1

###

POST https://localhost:5001/api/v1/mongo-person/multiple
Content-Type: application/json

[
    {
        "firstName": "Fox",
        "lastName": "Mulder",
    },
    {
        "firstName": "Dana",
        "lastName": "Scully"
    }
]
###
POST http://localhost:5000/api/v1/mongo-person/a6b178c0-8e5a-402a-aa0e-5128f5dd749c/custom-fields/
Content-Type: application/json

{
    "key" : "shirt size",
    "value": "lil-baby"
}

###
PUT http://localhost:5000/api/v1/mongo-person/a6b178c0-8e5a-402a-aa0e-5128f5dd749c/custom-fields/17ee079d-8bbb-4ca9-b9b9-d5b42f73baa9
Content-Type: application/json

{
    "key" : "shirt size",
    "value": "put again"
}

###
PATCH http://localhost:5000/api/v1/mongo-person/a6b178c0-8e5a-402a-aa0e-5128f5dd749c/custom-fields/17ee079d-8bbb-4ca9-b9b9-d5b42f73baa9
Content-Type: application/json

[
 {
  "op": "replace",
  "path": "/value",
  "value": "666666"
 },
    {
        "op": "replace",
        "path": "/key",
        "value": "7777777"
    }
]

###
DELETE http://localhost:5000/api/v1/mongo-person/38d3301a-ce8c-4dc3-8efd-a6f29e5bca31/custom-fields/6544756d-b782-4b57-a88f-7f03b61c0423
Content-Type: application/json

###
http://localhost:5000/api/v1/mongo/domain-event-custom-context
