POST https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/pets
Content-Type: application/json

{
    "petName": "Frodo",
    "petType": "Dog"
}
###
GET https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/pets?pageNumber=1&pageSize=10

###
GET https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/pets/bf9142f2-75b6-4ffc-ddf1-08d9f64dffba

###
GET https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/pets/all
###
GET https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/pets/bf9142f2-75b6-4ffc-ddf1-08d9f64dffba/changes?pageNumber=1&pageSize=10

###
GET https://localhost:5001/api/v1/ef-person/73686799-cf49-40f8-12e1-08d89c52a9fc/pets/export/csv?pageNumber=1&pageSize=10&fileName=test

###
POST https://localhost:5001/api/v1/ef/transactions/commit
