<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(FirebendTargetFrameworks)</TargetFrameworks>
        <Version>18.0.0</Version>
        <LangVersion>latestmajor</LangVersion>
        <Bumper>3</Bumper>
    </PropertyGroup>

    <PropertyGroup>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <NoWarn>$(NoWarn);1591,1570,1572,1573</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
      <AssemblyTitle>Firebend Auto Crud Web</AssemblyTitle>
      <Description>Firebend Auto Crud extension pack for exposing CRUD operations in aspnet core controllers</Description>
      <PackageTags>firebend;autocrud;crud;entity;web;asp;aspnet;mvc</PackageTags>
      <Authors>Firebend</Authors>
      <RepositoryUrl>https://github.com/firebend/auto-crud</RepositoryUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageProjectUrl>https://github.com/firebend/auto-crud</PackageProjectUrl>
      <PackageIcon>nuget-image.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Humanizer.Core" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" />
      <PackageReference Include="Microsoft.AspNetCore.JsonPatch" />
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Firebend.AutoCrud.Core\Firebend.AutoCrud.Core.csproj" />
    </ItemGroup>

</Project>
