name: Build and test

on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  build_and_test:
    name: Build and test    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Firebend.AutoCrud

    steps:
    - name : Checkout Repo
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore Firebend.AutoCrud.sln

    - name: Build
      run: dotnet build Firebend.AutoCrud.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Firebend.AutoCrud.sln --logger GitHubActions --no-restore --verbosity normal
