name: Build, Test, and Release

on:
  push:
    branches:
      - main

jobs:
  build_test_and_release:
    name: Build, test, and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore Firebend.AutoCrud.sln
    - name: Build
      run: dotnet build Firebend.AutoCrud.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Firebend.AutoCrud.sln --logger GitHubActions --no-restore --verbosity normal

    - name: Publish Core
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.Core/Firebend.AutoCrud.Core.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish EntityFramework
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.EntityFramework/Firebend.AutoCrud.EntityFramework.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish EntityFramework Elastic
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.EntityFramework.Elastic/Firebend.AutoCrud.EntityFramework.Elastic.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Generator
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.Generator/Firebend.AutoCrud.Generator.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Mongo
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.Mongo/Firebend.AutoCrud.Mongo.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Web
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.DomainEvents.MassTransit/Firebend.AutoCrud.DomainEvents.MassTransit.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Domain Events MassTransit
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.Web/Firebend.AutoCrud.Web.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Change Tracking
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.ChangeTracking/Firebend.AutoCrud.ChangeTracking.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Change Tracking Ef
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.ChangeTracking.EntityFramework/Firebend.AutoCrud.ChangeTracking.EntityFramework.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Change Tracking Mongo
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.ChangeTracking.Mongo/Firebend.AutoCrud.ChangeTracking.Mongo.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish Change Tracking Web
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.ChangeTracking.Web/Firebend.AutoCrud.ChangeTracking.Web.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish IO
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.Io/Firebend.AutoCrud.Io.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false

    - name: Publish IO Web
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: Firebend.AutoCrud.Io.Web/Firebend.AutoCrud.Io.Web.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
         TAG_COMMIT: false
